---
version: "2.1"
services:
  postfix:
    image: docker.io/juanluisbaptiste/postfix:latest
    container_name: postfix
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
    restart: unless-stopped
#
#
networks:
  default:
    external: true
    name: ${CONNET}